### PR TITLE
prevented XSS

### PR DESCRIPTION
**Pull request by dev-abir**

### CODE REVIEW

**Comment by dev-DTECH** [comment]
Did you test the changes that you have made?

**Comment by dev-DTECH** [comment]
Prevent XSS in the name also.

**Comment by dev-abir** [comment]
yes. Tested

**Comment by dev-DTECH** [comment]
> Prevent XSS in the name also.

Do this.

**Comment by dev-abir** [comment]
Prevent XSS in the name also.

What to do?

**Pull request merged**
