### PR TITLE
Bug fixed

### LINKED ISSUE #2: Chatting after signing out and re-sign in
When you send a message after signing out and re-sign in the app will display a blank message after that message.

I have checked that the blank message is not sent in the server.

Please help.

### PR DESCRIPTION
**Pull request by dev-abir**
Fixed [this](https://github.com/dev-DTECH/Network/issues/2#issue-589524936) bug

### CODE REVIEW

**Comment by dev-DTECH** [comment]
Did you test it in your pc ?

**Comment by dev-abir** [comment]
Yes

**Comment by dev-DTECH** [comment]
Nice

**Comment by dev-DTECH** [comment]
Thanks

**Pull request merged**
